# Setup
title:        From Caffeine to code
tagline:      A coding blog
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Girish Jha
  url:        /about/ 

permalink: /:year/:month/:title #pretty

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown